# Generated by Django 4.2.2 on 2023-06-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstValue', models.IntegerField()),
                ('secondValue', models.IntegerField()),
                ('operationName', models.CharField(max_length=50)),
                ('appName', models.CharField(max_length=50)),
            ],
        ),
    ]
